-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 28 Jun 2021 pada 07.36
-- Versi Server: 10.1.16-MariaDB
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bot`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `chatbot`
--

CREATE TABLE `chatbot` (
  `id` int(11) NOT NULL,
  `queries` varchar(10000) NOT NULL,
  `replies` varchar(10000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `chatbot`
--

INSERT INTO `chatbot` (`id`, `queries`, `replies`) VALUES
(5, 'Apa itu sakit kepala? | Apa itu sakit kepala\r\n\r\n\r\n', 'Sakit kepala adalah rasa sakit atau nyeri di kepala, yang bisa muncul secara bertahap atau mendadak. Nyeri bisa muncul di salah satu sisi kepala, atau di seluruh bagian kepala. Sakit kepala bisa membuat kepala terasa berdenyut, atau seperti terlilit kencang oleh tali.\r\n'),
(6, 'apa pengertian sakit kepala? | apa pengertian sakit kepala', 'Sakit kepala adalah rasa sakit atau nyeri di kepala, yang bisa muncul secara bertahap atau mendadak. Nyeri bisa muncul di salah satu sisi kepala, atau di seluruh bagian kepala. Sakit kepala bisa membuat kepala terasa berdenyut, atau seperti terlilit kencang oleh tali.\r\n'),
(7, 'apa penyebab sakit kepala? | apa penyebab sakit kepala', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(8, 'apa saja penyebab sakit kepala? | apa saja penyebab sakit kepala', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(9, 'apa yang menyebabkan sakit kepala? | apa yang menyebabkan sakit kepala', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(10, 'mengapa bisa sakit kepala? | mengapa bisa sakit kepala', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(11, 'kenapa bisa sakit kepala? | kenapa bisa sakit kepala', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(12, 'sakit kepala disebabkan oleh apa? | sakit kepala disebabkan oleh apa', 'Sakit kepala terjadi akibat aktifnya saraf nyeri di kepala. Kondisi ini dapat dipicu oleh beberapa perilaku sehari-hari, seperti kurang tidur, telat makan. Sakit kepala juga dapat dipicu oleh sejumlah penyakit, antara lain seperti infeksi telinga, sakit gigi, migrain, hipertensi, tumor otak. \r\n'),
(13, 'bagaimana mengetahui gejala sakit kepala? | bagaimana mengetahui gejala sakit kepala', 'Gejala sakit kepala adalah sakit atau nyeri di kepala, yang bisa menyebar ke wajah, leher, dan bahu. Penglihatan penderita juga dapat menjadi buram, serta lebih sensitif terhadap cahaya dan suara.'),
(14, 'apa saja tanda-tanda sakit kepala? | apa saja tanda-tanda sakit kepala', 'Gejala sakit kepala adalah sakit atau nyeri di kepala, yang bisa menyebar ke wajah, leher, dan bahu. Penglihatan penderita juga dapat menjadi buram, serta lebih sensitif terhadap cahaya dan suara.'),
(15, 'bagaimana kita mengetahui sedang sakit kepala? | bagaimana kita mengetahui sedang sakit kepala', 'Gejala sakit kepala adalah sakit atau nyeri di kepala, yang bisa menyebar ke wajah, leher, dan bahu. Penglihatan penderita juga dapat menjadi buram, serta lebih sensitif terhadap cahaya dan suara.'),
(16, 'apa saja jenis-jenis sakit kepala? | apa saja jenis-jenis sakit kepala', 'migrain, sakit kepala tegang, sakit kepala cluster, pusing\r\n'),
(17, 'apa saja macam-macam sakit kepala? | apa saja macam-macam sakit kepala', 'migrain, sakit kepala tegang, sakit kepala cluster, pusing\r\n'),
(18, 'jenis sakit kepala ada apa saja? | jenis sakit kepala ada apa saja', 'migrain, sakit kepala tegang, sakit kepala cluster, pusing\r\n'),
(19, 'bagaimana cara mengatasi sakit kepala? bagaimana cara mengatasi sakit kepala', 'istirahat yang cukup, tidur diruangan yang gelap, pijatan dititik-titik tertentu, kompres menggunakan air hangat maupun dingin, atau minum obat-obatan medis. \r\n'),
(20, 'bagaimana cara mengobati sakit kepala? bagaimana cara mengobati sakit kepala', 'istirahat yang cukup, tidur diruangan yang gelap, pijatan dititik-titik tertentu, kompres menggunakan air hangat maupun dingin, atau minum obat-obatan medis. \r\n'),
(21, 'bagaimana mencegah sakit kepala? | bagaimana mencegah sakit kepala', 'istirahat yang cukup, tidur diruangan yang gelap, pijatan dititik-titik tertentu, kompres menggunakan air hangat maupun dingin, atau minum obat-obatan medis. \r\n'),
(22, 'bagaimana tips mengatasi sakit kepala? | bagaimana tips mengatasi sakit kepala', 'istirahat yang cukup, tidur diruangan yang gelap, pijatan dititik-titik tertentu, kompres menggunakan air hangat maupun dingin, atau minum obat-obatan medis. \r\n'),
(23, 'bagaimana cara mencegah sakit kepala? | bagaimana cara mencegah sakit kepala', 'istirahat yang cukup, tidur diruangan yang gelap, pijatan dititik-titik tertentu, kompres menggunakan air hangat maupun dingin, atau minum obat-obatan medis. \r\n'),
(24, 'apa penyebab sakit kepala saat bangun tidur? | apa penyebab sakit kepala saat bangun tidur', 'Rasa pusing atau sakit kepala sering kita rasakan saat bangun tidur. Hal ini utamanya disebabkan oleh gaya hidup yang makin sibuk dan kebiasaan tak sehat.\r\n'),
(25, 'saya sering merasa kepala saya pusing saat bangun tidur, itu dikarenakan oleh apa ya? | saya sering merasa kepala saya pusing saat bangun tidur, itu dikarenakan oleh apa ya', 'Rasa pusing atau sakit kepala sering kita rasakan saat bangun tidur. Hal ini utamanya disebabkan oleh gaya hidup yang makin sibuk dan kebiasaan tak sehat.\r\n'),
(26, 'kenapa kepala saya terasa sakit hanya sebelah?| kenapa kepala saya terasa sakit hanya sebelah', 'Sakit kepala sebelah, alias cluster headache, adalah jenis sakit kepala yang ditandai dengan rasa nyeri yang tiba-tiba muncul di belakang mata atau area sekitar mata, namun hanya di salah satu sisi kepala. Rasa nyeri bisa bertahan setidaknya 15 menit hingga tiga jam.\r\n'),
(27, 'mengapa sebelah kepala saya terasa sakit? | mengapa sebelah kepala saya terasa sakit', 'Sakit kepala sebelah, alias cluster headache, adalah jenis sakit kepala yang ditandai dengan rasa nyeri yang tiba-tiba muncul di belakang mata atau area sekitar mata, namun hanya di salah satu sisi kepala. Rasa nyeri bisa bertahan setidaknya 15 menit hingga tiga jam.\r\n'),
(28, 'mengapa saya sering merasakan sakit kepala berulang? | mengapa saya sering merasakan serangan sakit kepala berulang', 'serangan sakit kepala berulang yang diikuti rasa nyeri yang biasanya parah dan sering membuat tidak berdaya biasanya disebut migrain.\r\n'),
(29, 'mengapa saya merasa tidak nafsu untuk makan? | mengapa saya merasa tidak nafsu untuk makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(30, 'kenapa saya kehilangan nafsu makan? | kenapa saya kehilangan nafsu makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(31, 'mengapa saya merasa sulit untuk makan? | mengapa saya merasa sulit untuk makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(32, 'kenapa saya sulit untuk makan? | kenapa saya sulit untuk makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(33, 'tidak nafsu makan disebabkan oleh apa? | tidak nafsu makan disebabkan oleh apa', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(34, 'mengapa saya tidak selera melihat makananan didepan saya? | mengapa saya tidak selera melihat makanan didepan saya', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(35, 'saya merasa nafsu makan berkurang, kenapa ya? | saya merasa nafsu makan berkurang, kenapa ya', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(36, 'saya lapar tapi tidak nafsu makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(37, 'saya merasa malah untuk makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(38, 'saya merasa lapar tapi saya malas makan', 'Tidak nafsu makan umumnya dialami oleh orang yang sedang sakit. Akan tetapi, penyebab kehilangan nafsu makan tidak melulu karena sakit, melainkan dapat juga akibat efek samping obat-obatan, stres berlebihan, hingga kondisi medis tertentu.\r\n'),
(39, 'bagaimana cara mengatasi tidak nafsu makan? | bagaimana cara mengatasi tidak nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(40, 'bagaimana tips mengatasi tidak nafsu makan? | bagaimana tips mengatasi tidak nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(41, 'bagaimana cara mengatasi malas makan? | bagaimana cara mengatasi malas makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(42, 'bagaimana tips mengatasi malas makan? | bagaimana tips mengatasi malas makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(43, 'bagaimana cara mengatasi kurang nafsu makan? | bagaimana mengatasi kurang nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(44, 'bagaimana tips mengatasi kurang nafsu makan? | bagaimana tips mengatasi kurang nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(45, 'bagaimana meningkatkan nafsu makan? | bagaimana meningkatkan nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(46, 'bagaimana cara meningkatkan nafsu makan? | bagaimana cara meningkatkan nafsu makan', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(47, 'apa cara agar nafsu makan meningkat? | apa cara agar nafsu makan meningkat', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(48, 'dengan cara apa agar nafsu makan dapat teratasi? | dengan cara apa agar nafsu makan dapat teratasi', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(49, 'apa yang harus dilakukan agar nafsu makan saya kembali? | apa yang harus dilakukan agar nafsu makan saya kembali', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(50, 'apa yang harus saya lakukan supaya nafsu makan saya meningkat? | apa yang harus saya lakukan supaya nafsu makan saya meningkat\r\n\r\n', 'memvariasi menu makanan setiap hari, makan dengan porsi yang sedikit namun sering, makan bersama orang-orang terdekat, berpikir positif, jangan stres berlebihan, lakukan aktifitas produktif, olahraga, serta jauhi narkoba, rokok dan alkohol\r\n'),
(51, 'apa penyebab tidur tidak nyenyak? | apa penyebab tidur tidak nyenyak', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(52, 'apa penyebab sulit tidur? | apa penyebab sulit tidur', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(53, 'mengapa saya sulit sekali untuk tidur dengan nyenyak? | mengapa saya sulit sekali untuk tidur dengan nyenyak', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(54, 'sulit tidur disebabkan oleh apa? | sulit tidur disebabkan oleh apa', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(55, 'mengapa sulit tidur bisa terjadi? | mengapa sulit tidur bisa terjadi', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(56, 'mengapa susah tidur bisa terjadi? | mengapa susah tidur bisa terjadi', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(57, 'apa penyebab susah tidur? | apa penyebab susah tidur', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(58, 'bagaimana sulit tidur bisa terjadi? | bagaimana sulit tidur bisa terjadi', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(59, 'bagaimana susah tidur bisa terjadi? | bagaimana susah tidur bisa terjadi', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(60, 'bagaimana tidur tidak nyenyak bisa terjadi? | bagaimana tidur tidak nyenyak bisa terjadi', 'tidur tidak nyenyak disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(61, 'mengapa insomnia bisa terjadi? | mengapa insomnia bisa terjadi', 'insomnia disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(62, 'apa penyebab insomnia? | apa penyebab insomnia', 'insomnia disebabkan oleh kebiasaan sebelum tidur yang tidak baik, gangguan mental, sedang stres, sedang depresi, minum kopi menjelang tidur, minum alkohol, merokok sebelum tidur, ada penyakit tertentu atau kebiasaan memainkan gadget sebelum tidur.\r\n'),
(63, 'bagaimana cara mengatasi kesulitan untuk tidur? | bagaimana cara mengatasi kesulitan untuk tidur', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(64, 'bagaimana cara mengobati susah tidur? | bagaimana cara mengobati susah tidur', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(65, 'bagaimana agar susah tidur tidak terjadi lagi? | bagaimana agar susah tidur tidak terjadi lagi', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(66, 'apakah ada tips mengatasi susah tidur? | apakah ada tips mengatasi susah tidur', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(67, 'bagaimana susah tidur dapat teratasi? | bagaimana susah tidur dapat teratasi', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(68, 'bagaimana sulit tidur dapat diatasi? | bagaimana sulit tidur dapat diatasi', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(69, 'dengan cara apa susah tidur dapat di obati? | dengan cara apa susah tidur dapat di obati', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(70, 'bagaimana cara mengatasi insomnia? | bagaimana cara mengatasi insomnia', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(71, 'bagaimana cara mencegah insomnia terjadi? | bagaimana cara mencegah insomnia terjadi', 'Menciptakan lingkungan untuk tidur yang baik,  tidak bekerja hingga larut malam, tidur sesuai jadwal, rutin berolahraga, menghentikan penggunaan gadget 30 menit sebelum tidur, mengelola stres dengan baik, menghindari alkohol, kafein dan rokok.\r\n'),
(72, 'apa saja gejala susah tidur? | apa saja gejala susah tidur', 'Bangun dan tidur pada waktu yang tidak teratur, Kesulitan tidur pada malam hari, Bernapas dengan irama yang tidak normal saat tidur, Mengalami mimpi buruk, mendengkur, sering merasa mengantuk di siang hari, sering merasa lelah\r\n'),
(73, 'apa saja gejala sulit tidur? | apa saja gejala sulit tidur', 'Bangun dan tidur pada waktu yang tidak teratur, Kesulitan tidur pada malam hari, Bernapas dengan irama yang tidak normal saat tidur, Mengalami mimpi buruk, mendengkur, sering merasa mengantuk di siang hari, sering merasa lelah\r\n'),
(74, 'apa saja gejala sukar tidur? | apa saja gejala sukar tidur', 'Bangun dan tidur pada waktu yang tidak teratur, Kesulitan tidur pada malam hari, Bernapas dengan irama yang tidak normal saat tidur, Mengalami mimpi buruk, mendengkur, sering merasa mengantuk di siang hari, sering merasa lelah\r\n'),
(75, 'apa saja gejala insomnia? | apa saja gejala insomnia', 'Bangun dan tidur pada waktu yang tidak teratur, Kesulitan tidur pada malam hari, Bernapas dengan irama yang tidak normal saat tidur, Mengalami mimpi buruk, mendengkur, sering merasa mengantuk di siang hari, sering merasa lelah\r\n'),
(76, 'mengapa saya mudah merasa takut? | mengapa saya mudah merasa takut', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(77, 'kenapa saya sering merasa takut? | kenapa saya sering merasa takut', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(78, 'mengapa saya sering merasa takut? | mengapa saya sering merasa takut', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(79, 'saya sering merasa ketakutan, itu kenapa ya? saya sering merasa ketakutan, itu kenapa ya', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(80, 'apa penyebab mudah merasa takut? | apa penyebab mudah merasa takut', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(81, 'faktor apa yang mebuat rasa takut berlebihan? | faktor apa yang membuat rasa takut berlebihan', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(82, 'bagaimana rasa takut itu bisa muncul? | bagaimana rasa takut itu bisa muncul', 'Sedang dilanda stres yang berlebihan, memiliki masalah yang masih belum terselesaikan, tidak ada seseorang yang dapat diajak bertukar pikiran, kurang mendekatkan diri kepada tuhan, sedanng memiliki beba tanggung jawab yang besar, waspada akan terjadinya gangguan kecemasan\r\n'),
(83, 'apakah mudah merasa takut berbahaya? | apakah mudah merasa takut berbahaya', 'Rasa takut merupakan hal yang wajar terjadi pada semua orang. Namun jika ketakutan tersebut sudah terjadi secara berlebihan dan mengganggu aktivitas sehari-hari dalam kehidupan akan menjadi berbahaya.\r\n'),
(84, 'apakah sering merasa takut itu berbahaya? | apakah sering merasa takut itu berbahaya', 'Rasa takut merupakan hal yang wajar terjadi pada semua orang. Namun jika ketakutan tersebut sudah terjadi secara berlebihan dan mengganggu aktivitas sehari-hari dalam kehidupan akan menjadi berbahaya.\r\n'),
(85, 'apa saja gejala yang dialami saat merasa takut? | apa saja gejala yang dialami saat merasa takut', 'Saat merasa takut, ada beberapa gejala atau perubahan pada fisik dan emosional yang umumnya akan muncul seperti detak jantung tidak teratur, nafas tersengal-sengal, cepat berkeringat, sakit perut, sakit kepala, mual, pusing, gagap, kehilangan selera makan, tidak bisa tidur atau menangis\r\n'),
(86, 'bagaimana mengetahui kalau kita sedang merasa takut? | bagaimana mengetahui kalau kita sedang merasa takut', 'Saat merasa takut, ada beberapa gejala atau perubahan pada fisik dan emosional yang umumnya akan muncul seperti detak jantung tidak teratur, nafas tersengal-sengal, cepat berkeringat, sakit perut, sakit kepala, mual, pusing, gagap, kehilangan selera makan, tidak bisa tidur atau menangis\r\n'),
(87, 'bagaimana cara mengatasi rasa takut? | bagaimana cara mengatasi rasa takut', 'alihkan perhatian, coba bernafas yang teratur, hadapi ketakutan, pikirkan hal-hal yang positif, curhat kepada orang lain, hindari mengonsumsi alkohol dan rokok secara berlebihan\r\n'),
(88, 'bagaimana cara mengusir rasa takut? | bagaimana cara mengusir rasa takut', 'alihkan perhatian, coba bernafas yang teratur, hadapi ketakutan, pikirkan hal-hal yang positif, curhat kepada orang lain, hindari mengonsumsi alkohol dan rokok secara berlebihan\r\n'),
(89, 'bagaimana cara mengobati rasa takut? | bagaimana cara mengobati rasa takut', 'alihkan perhatian, coba bernafas yang teratur, hadapi ketakutan, pikirkan hal-hal yang positif, curhat kepada orang lain, hindari mengonsumsi alkohol dan rokok secara berlebihan\r\n'),
(90, 'dengan cara apa kita bisa mengatasi rasa takut? | dengan cara apa kita bisa mengatasi rasa takut', 'alihkan perhatian, coba bernafas yang teratur, hadapi ketakutan, pikirkan hal-hal yang positif, curhat kepada orang lain, hindari mengonsumsi alkohol dan rokok secara berlebihan\r\n'),
(91, 'dengan cara apa kita bisa mengusir rasa takut? | dengan cara apa kita bisa mengusir rasa takut', 'alihkan perhatian, coba bernafas yang teratur, hadapi ketakutan, pikirkan hal-hal yang positif, curhat kepada orang lain, hindari mengonsumsi alkohol dan rokok secara berlebihan\r\n'),
(92, 'mengapa saya mudah merasa cemas? | mengapa saya mudah merasa cemas', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(93, 'mengapa saya mudah merasa tegang? | mengapa saya mudah merasa tegang', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(94, 'mengapa saya mudah merasa khawatir? | mengapa saya mudah merasa khawatir', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(95, 'mengapa saya sering merasa cemas? | mengapa saya sering merasa cemas', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(96, 'mengapa saya sering merasa tegang? | mengapa saya sering merasa tegang', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(97, 'mengapa saya sering merasa khawatir? |\r\nmengapa saya sering merasa khawatir', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(98, 'kenapa saya mudah merasa cemas? | kenapa saya mudah merasa cemas', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(99, 'kenapa saya mudah merasa tegang? | kenapa saya mudah merasa tegang', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n'),
(100, 'kenapa saya mudah merasa khawatir? | kenapa saya mudah merasa khawatir', 'cemas, tegang, khawatir, dan gelisah atau sering disebut kecemasan merupakan reaksi normal saat kamu mengalami stres.  Kecemasan ini dapat dialami dari berbagai hal, seperti takut terserang penyakit hingga saat akan mengambil atau menerima keputusan yang berat, trauma psikologis, keturunan, gangguan kepribadian, efek samping obat tertentu.\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chatbot`
--
ALTER TABLE `chatbot`
  ADD PRIMARY KEY (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
